apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tcqo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tcqo
    app.kubernetes.io/part-of: byoc-app-xokx
  name: tcqoljiv
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: tcqo
    weight: null
status: {}
